#!/usr/bin/env node
/**
 * Hazel Canvas Dashboard Server
 *
 * Unified server for Entity Graph + Intents Dashboard + Memory Viewer
 * Serves the dashboard UI and provides live API for intents from SQLite
 *
 * Usage: node dashboard-server.js [port]
 * Default port: 8081
 *
 * Environment variables:
 *   HAZEL_WORKSPACE  — path to Hazel workspace (default: ~/.hazel/workspace)
 *   DASHBOARD_PORT   — server port (default: 8081)
 *   DASHBOARD_HOST   — listen address (default: 127.0.0.1)
 *
 * Authentication:
 *   If ~/.hazel/dashboard.key exists, all routes (except /health) require
 *   a valid HMAC token via ?token= query param or hazel_session cookie.
 *   Tokens are generated by the Hazel `dashboard_link` tool.
 */

const http = require('http');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { URL } = require('url');

// Load better-sqlite3
let Database;
try {
  Database = require('better-sqlite3');
} catch {
  console.error('Error: better-sqlite3 not found. Install with:');
  console.error('  cd canvas && npm install');
  process.exit(1);
}

// --- Configuration ---
const PORT = parseInt(process.env.DASHBOARD_PORT || process.argv[2]) || 8081;
const HOST = process.env.DASHBOARD_HOST || '127.0.0.1';

// --- Token Authentication ---
const SECRET_PATH = path.join(os.homedir(), '.hazel', 'dashboard.key');
let _cachedSecret = null;
let _lastSecretCheck = 0;
const SECRET_CHECK_INTERVAL = 30_000; // re-read secret file every 30s

function getSecret() {
  const now = Date.now();
  if (now - _lastSecretCheck < SECRET_CHECK_INTERVAL) return _cachedSecret;
  _lastSecretCheck = now;
  try {
    _cachedSecret = fs.readFileSync(SECRET_PATH, 'utf-8').trim();
  } catch {
    _cachedSecret = null;
  }
  return _cachedSecret;
}

function validateToken(token, secret) {
  if (!token || !secret) return false;
  const dot = token.indexOf('.');
  if (dot < 1) return false;
  const expiryHex = token.slice(0, dot);
  const providedHmac = token.slice(dot + 1);
  const expiry = parseInt(expiryHex, 16);
  if (isNaN(expiry) || expiry < Math.floor(Date.now() / 1000)) return false;
  const expectedHmac = crypto
    .createHmac('sha256', secret)
    .update(expiryHex)
    .digest('hex');
  try {
    return crypto.timingSafeEqual(
      Buffer.from(providedHmac, 'hex'),
      Buffer.from(expectedHmac, 'hex')
    );
  } catch {
    return false;
  }
}

function parseCookies(req) {
  const cookies = {};
  (req.headers.cookie || '').split(';').forEach(c => {
    const [key, ...val] = c.trim().split('=');
    if (key) cookies[key.trim()] = val.join('=').trim();
  });
  return cookies;
}

function tokenRemainingSeconds(token) {
  const dot = token.indexOf('.');
  if (dot < 1) return 0;
  const expiry = parseInt(token.slice(0, dot), 16);
  return Math.max(0, expiry - Math.floor(Date.now() / 1000));
}

function sendExpiredPage(res) {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hazel Canvas — Session Expired</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0f0f1a;
      color: #e0e0e0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
    }
    .card {
      background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
      border: 1px solid #2a2a4a;
      border-radius: 16px;
      padding: 48px;
      max-width: 440px;
      text-align: center;
    }
    .icon { font-size: 48px; margin-bottom: 16px; }
    h1 { font-size: 22px; color: #e94560; margin-bottom: 12px; }
    p { color: #a0a0c0; line-height: 1.6; margin-bottom: 8px; }
    .hint {
      margin-top: 24px;
      padding: 16px;
      background: rgba(233,69,96,0.08);
      border: 1px solid rgba(233,69,96,0.2);
      border-radius: 8px;
      color: #e0e0e0;
      font-size: 14px;
    }
    code {
      background: rgba(255,255,255,0.08);
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">&#x1f512;</div>
    <h1>Session Expired</h1>
    <p>This dashboard link has expired or is invalid.</p>
    <div class="hint">
      Ask Hazel for a new link:<br>
      <code>"Give me a dashboard link"</code>
    </div>
  </div>
</body>
</html>`;
  res.writeHead(401, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(html);
}

// Resolve workspace: env var > parent of script dir > config file > default
function resolveWorkspace() {
  if (process.env.HAZEL_WORKSPACE) {
    return process.env.HAZEL_WORKSPACE.replace(/^~/, os.homedir());
  }

  // If this script lives inside a workspace's canvas/ dir, use the parent
  const parent = path.dirname(__dirname);
  if (path.basename(__dirname) === 'canvas'
      && (fs.existsSync(path.join(parent, 'data'))
          || fs.existsSync(path.join(parent, 'memory')))) {
    return parent;
  }

  // Try reading Hazel config
  const configPath = path.join(os.homedir(), '.hazel', 'config.json');
  try {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    const ws = config?.agents?.defaults?.workspace
      || config?.agents?.defaults?.Workspace;
    if (ws) return ws.replace(/^~/, os.homedir());
  } catch { /* config not found or unreadable */ }

  return path.join(os.homedir(), '.hazel', 'workspace');
}

const WORKSPACE = resolveWorkspace();
const CANVAS_DIR = __dirname;
const DB_PATH = path.join(WORKSPACE, 'data', 'intents.db');

// MIME types
const MIME_TYPES = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.jsonl': 'application/jsonl; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.md': 'text/markdown; charset=utf-8',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

// Lazy database connection — retries on each request if not yet available
let db = null;
function getDb() {
  if (db) return db;
  try {
    if (fs.existsSync(DB_PATH)) {
      db = new Database(DB_PATH, { readonly: true });
      console.log('  Database:  ', DB_PATH);
    }
  } catch (err) {
    console.error('  Database:   FAILED -', err.message);
  }
  return db;
}
// Attempt initial connection
getDb();
if (!db) {
  console.log('  Database:   (not yet created — will retry on first request)');
}

// --- API Handlers ---

function handleApiIntents(res, url) {
  if (!getDb()) return sendJson(res, 200, { intents: [], count: 0 });

  const params = url.searchParams;

  let sql = `
    SELECT
      i.*,
      GROUP_CONCAT(DISTINCT il.entity_path) as linked_paths,
      GROUP_CONCAT(DISTINCT il.entity_id) as linked_ids
    FROM intents i
    LEFT JOIN intent_links il ON i.id = il.intent_id
    WHERE 1=1
  `;
  const args = [];

  // Filters
  const status = params.getAll('status');
  if (status.length > 0) {
    sql += ` AND i.status IN (${status.map(() => '?').join(',')})`;
    args.push(...status);
  }

  const type = params.getAll('type');
  if (type.length > 0) {
    sql += ` AND i.type IN (${type.map(() => '?').join(',')})`;
    args.push(...type);
  }

  const q = params.get('q');
  if (q) {
    sql += ` AND (i.title LIKE ? OR i.body LIKE ?)`;
    args.push(`%${q}%`, `%${q}%`);
  }

  const entityPath = params.get('entity_path');
  if (entityPath) {
    sql += ` AND il.entity_path = ?`;
    args.push(entityPath);
  }

  sql += ` GROUP BY i.id ORDER BY
    CASE i.status
      WHEN 'active' THEN 1
      WHEN 'snoozed' THEN 2
      ELSE 3
    END,
    COALESCE(i.due_at, i.start_at, '9999') ASC
  `;

  const limit = parseInt(params.get('limit')) || 200;
  const offset = parseInt(params.get('offset')) || 0;
  sql += ` LIMIT ? OFFSET ?`;
  args.push(limit, offset);

  try {
    const rows = db.prepare(sql).all(...args);

    // Parse linked paths/ids into arrays
    const intents = rows.map(row => ({
      ...row,
      linked_paths: row.linked_paths ? row.linked_paths.split(',') : [],
      linked_ids: row.linked_ids ? row.linked_ids.split(',') : [],
    }));

    sendJson(res, 200, { intents, count: intents.length });
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
}

function handleApiIntent(res, id) {
  if (!getDb()) return sendJson(res, 404, { error: 'No database' });

  try {
    const intent = db.prepare('SELECT * FROM intents WHERE id = ?').get(id);
    if (!intent) {
      sendJson(res, 404, { error: 'Intent not found' });
      return;
    }

    const links = db.prepare('SELECT * FROM intent_links WHERE intent_id = ?').all(id);
    sendJson(res, 200, { intent, links });
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
}

function handleApiStats(res) {
  if (!getDb()) return sendJson(res, 200, { stats: [], overdue: 0, upcoming: 0 });

  try {
    const stats = db.prepare(`
      SELECT
        status,
        type,
        COUNT(*) as count
      FROM intents
      GROUP BY status, type
    `).all();

    const overdue = db.prepare(`
      SELECT COUNT(*) as count
      FROM intents
      WHERE status = 'active'
        AND due_at IS NOT NULL
        AND due_at < datetime('now')
    `).get();

    const upcoming = db.prepare(`
      SELECT COUNT(*) as count
      FROM intents
      WHERE status = 'active'
        AND (due_at IS NOT NULL OR start_at IS NOT NULL)
        AND COALESCE(due_at, start_at) BETWEEN datetime('now') AND datetime('now', '+7 days')
    `).get();

    sendJson(res, 200, {
      stats,
      overdue: overdue?.count || 0,
      upcoming: upcoming?.count || 0
    });
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
}

function handleApiMemoryDaily(res) {
  try {
    const memoryDir = path.join(WORKSPACE, 'memory');
    if (!fs.existsSync(memoryDir)) {
      sendJson(res, 200, { dates: [] });
      return;
    }
    const files = fs.readdirSync(memoryDir)
      .filter(f => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
      .map(f => f.replace('.md', ''))
      .sort()
      .reverse();
    sendJson(res, 200, { dates: files });
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
}

function handleApiChanges(res, url) {
  const params = url.searchParams;
  const changesPath = path.join(WORKSPACE, 'memory', '_index', 'changes.jsonl');

  try {
    if (!fs.existsSync(changesPath)) {
      sendJson(res, 200, { changes: [], count: 0 });
      return;
    }

    const lines = fs.readFileSync(changesPath, 'utf-8')
      .split('\n')
      .filter(l => l.trim())
      .map(l => { try { return JSON.parse(l); } catch { return null; } })
      .filter(Boolean);

    let filtered = lines;

    const since = params.get('since');
    if (since) filtered = filtered.filter(c => c.ts >= since);

    const until = params.get('until');
    if (until) filtered = filtered.filter(c => c.ts <= until);

    const entityId = params.get('entity_id');
    if (entityId) filtered = filtered.filter(c => c.entity_id === entityId);

    const entityType = params.get('entity_type');
    if (entityType) filtered = filtered.filter(c => c.entity_type === entityType);

    const limit = parseInt(params.get('limit')) || 100;
    filtered = filtered.slice(-limit).reverse();

    sendJson(res, 200, { changes: filtered, count: filtered.length });
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
}

// --- Response Helpers ---

function sendJson(res, status, data) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

// --- Static File Handler ---

function serveFile(res, filePath) {
  fs.readFile(filePath, (err, data) => {
    if (err) {
      if (err.code === 'ENOENT') {
        res.writeHead(404);
        res.end('Not found');
      } else {
        res.writeHead(500);
        res.end('Server error');
      }
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    const contentType = MIME_TYPES[ext] || 'application/octet-stream';
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(data);
  });
}

function serveWorkspaceFile(res, relativePath) {
  // Security: resolve and check it's within workspace
  const fullPath = path.resolve(WORKSPACE, relativePath);
  if (!fullPath.startsWith(path.resolve(WORKSPACE))) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }
  serveFile(res, fullPath);
}

// --- Main Request Handler ---

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const pathname = url.pathname;

  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Health check (exempt from auth)
  if (pathname === '/health') {
    sendJson(res, 200, {
      status: 'ok',
      uptime: process.uptime(),
      workspace: WORKSPACE,
      database: db ? 'connected' : 'not available',
      auth: !!getSecret(),
    });
    return;
  }

  // --- Token authentication ---
  const secret = getSecret();
  if (secret) {
    const cookies = parseCookies(req);
    const queryToken = url.searchParams.get('token');
    const cookieToken = cookies['hazel_session'];
    const token = queryToken || cookieToken;

    if (!validateToken(token, secret)) {
      // API routes get JSON 401; page routes get the expired HTML
      if (pathname.startsWith('/api/')) {
        sendJson(res, 401, { error: 'Session expired. Ask Hazel for a new dashboard link.' });
      } else {
        sendExpiredPage(res);
      }
      return;
    }

    // If token came via query param, set a cookie so subsequent requests work
    if (queryToken && validateToken(queryToken, secret)) {
      const maxAge = tokenRemainingSeconds(queryToken);
      res.setHeader(
        'Set-Cookie',
        `hazel_session=${queryToken}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}`
      );
    }
  }

  // Dashboard HTML (served from canvas dir)
  if (pathname === '/' || pathname === '/dashboard.html') {
    return serveFile(res, path.join(CANVAS_DIR, 'dashboard.html'));
  }

  // API routes
  if (pathname === '/api/intents') {
    return handleApiIntents(res, url);
  }

  if (pathname.startsWith('/api/intents/')) {
    const id = pathname.split('/')[3];
    return handleApiIntent(res, id);
  }

  if (pathname === '/api/stats') {
    return handleApiStats(res);
  }

  if (pathname === '/api/memory/daily') {
    return handleApiMemoryDaily(res);
  }

  if (pathname === '/api/changes') {
    return handleApiChanges(res, url);
  }

  // Workspace files (memory/*, data/*, etc.)
  if (pathname.startsWith('/memory/') || pathname.startsWith('/data/')) {
    const relativePath = pathname.slice(1); // strip leading /
    return serveWorkspaceFile(res, relativePath);
  }

  // Fallback: try workspace root files (MEMORY.md, etc.)
  if (pathname.endsWith('.md') || pathname.endsWith('.jsonl')) {
    const relativePath = pathname.slice(1);
    return serveWorkspaceFile(res, relativePath);
  }

  // Static assets from canvas dir
  const canvasAsset = path.join(CANVAS_DIR, pathname);
  if (fs.existsSync(canvasAsset) && fs.statSync(canvasAsset).isFile()) {
    return serveFile(res, canvasAsset);
  }

  res.writeHead(404);
  res.end('Not found');
});

server.listen(PORT, HOST, () => {
  const authEnabled = !!getSecret();
  console.log('');
  console.log('Hazel Canvas Dashboard');
  console.log('\u2500'.repeat(40));
  console.log(`   Listen:    http://${HOST}:${PORT}`);
  console.log(`   Workspace: ${WORKSPACE}`);
  console.log(`   Auth:      ${authEnabled ? 'enabled (token required)' : 'disabled (open access)'}`);
  console.log('');
  console.log('   Dashboard: /');
  console.log('   API:       /api/intents, /api/stats, /api/changes');
  console.log('   Health:    /health');
  console.log('\u2500'.repeat(40));
});

// Graceful shutdown
function shutdown() {
  console.log('\nShutting down...');
  if (db) db.close();
  server.close(() => {
    console.log('Server closed.');
    process.exit(0);
  });
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
